### PR TITLE
Fix fetched_records to skip messages with offset lesser than given fetch_offset

### PR DESCRIPTION
**Pull request by 88manpreet**
The fix is for the issue https://github.com/dpkp/kafka-python/issues/1214

### CODE REVIEW

**Comment by 88manpreet** [comment]
@dpkp I don't think I have permission to rebuild the above-failed travis job (https://travis-ci.org/dpkp/kafka-python/jobs/277078233). Can you please trigger the same for me or let me know the way I can?

**Comment by dpkp** [comment]
I don't understand how this would fix the issue you've outlined.

**Comment by 88manpreet** [comment]
@dpkp Earlier we were just comparing current-offset (record.offset) with the desired offset (fetch_offset) once and return immediately after setting desired offset to current-offset+1 inside 'take' api (https://github.com/dpkp/kafka-python/blob/master/kafka/consumer/fetcher.py#L943)

Note: As part of my testing I observed that this issue was only seen with topics with 'COMPRESSED' messages. On testing with UNCOMPRESSED messages, I observed that the reason it wasn't seen was that the current-offset (message.offset) was either equal to fetch_offset or 1 less than the fetch_offset.
 
Let's pick the scenario where max_records is 1 ==> part_records will always have 1 record.
Let's say current-offset (message: m): 80, Desired-offset: 90
Before fix:
----------
The message 'm' is skipped since (80 < 90) and we return, len(part_records) == 1, which is incorrect since we don't havn't reached the record with offset 90. 
Also, inside the 'take' api, we set the Desired-offset (fetch_offset) to 81, which is also incorrect.
As a result in next call to _append returns the message with offset 81.

With Fix:
--------
I keep in while loop unless I get max_records (1) message(s). As a result, it iterates from message with current-offset 80 upto the message with current-offset (90: desired-offset). Also, I return the length of relevant messages found.

Hope this helps.

**Comment by dpkp** [comment]
Thanks for the detail. I see how this approach would work now. I would prefer to address the issue slightly differently, so I'm going to close this. But I'll put up a separate PR to fix the same issue.

**Comment by 88manpreet** [comment]
Thanks @dpkp :) We will use this fix for the time being as it blocks some of our services. Kindly link your PR to this issue and whenever it's ready, we would pick that up.
On a side-note, do you see any obvious issue or side-effect with the above fix? Let me know if any debug logs are needed.

**Comment by dpkp** [comment]
The way you've done it here should work, but I haven't tested it. I landed a change to master w/ a test to verify. It will be included in the next release.

**Pull request closed without merging**
