### PR TITLE
changed for loop to use enumerate()

### PR DESCRIPTION
**Pull request by TheAtomicOption**
enumerate() is cleaner and allows removing an assignment statement.

### CODE REVIEW

**Comment by dpkp** [comment]
I chose not to use enumerate because the loop explicitly modifies the list itself and that typically doesn't play well with in place iterators

**Comment by TheAtomicOption** [comment]
It's not changing the count or order of records, just the values so that _shouldn't_ be an issue in python as [the example in the PEP itself shows doing exactly that](https://docs.python.org/2.3/whatsnew/section-enumerate.html). 

That said, all these build checks failed, which really surprised me since it seemed to work on my clone. The only issue I expected on seeing the code was maybe a performance drag from the change in element size of the data from record --> (record, stuff), but that was there to start with.

**Comment by dpkp** [comment]
Apologies -- all test fixtures were failing due to an unrelated issue. Please pull latest changes from master and re-run tests.

**Comment by TheAtomicOption** [comment]
Yay it passes, and I am no longer confused! :)

**Comment by dpkp** [comment]
Thanks for the fixup and link to PEP w/ example!

**Pull request merged**
