### PR TITLE
Fix SSL connection testing in Python 3.7

### PR DESCRIPTION
**Pull request by silentben**
This change is [Reviewable](https://reviewable.io/reviews/dpkp/kafka-python/1669)

### CODE REVIEW

**Comment by silentben** [comment]
This is based on @seanthegeek's [pull request 1661](https://github.com/dpkp/kafka-python/pull/1661) but cleaned up a bit (just one commit to one specific file)

I'm not sure why it's still showing the integration test as "pending" when it actually completed successfully if you click through at https://travis-ci.org/dpkp/kafka-python/builds/464615729?utm_source=github_status&utm_medium=notification

This closes #1549

**Comment by danjo133** [comment]
What is stalling this? Support for 3.7 would be super nice!

**Comment by silentben** [comment]
@dpkp happy new year! is it possible to merge this so we can run on python 3.7?

**Comment by jeffwidman** [comment]
Thanks @silentben  / @seanthegeek!

Merging now.

**Comment by AlmogCohen** [comment]
Thanks! Was it released to PyPi?

**Comment by AlmogCohen** [comment]
I'm asking as I keep getting this error locally :)

**Comment by AlmogCohen** [comment]
I'd be happy if you can release that so I take my project back to 3.7 :) Thanks!

**Comment by dpkp** [comment]
We have been unable to get travis trsts to run on py37. Can you help us
figure that out?

**Comment by AlmogCohen** [comment]
I can take a look. I got a bit confused in the repo as I thought it was already merged. Where would I find the latest work that includes the 3.7 fix and failed travis build? some branch?

**Comment by dpkp** [comment]
Open PR is at https://github.com/dpkp/kafka-python/pull/1614

**Pull request merged**
