### PR TITLE
Catch thrown OSError by python 3.7 when creating a connection

### PR DESCRIPTION
**Pull request by danjo133**
This is needed to use kafka-python with python 3.7.

It builds on #1669 and the solution is a slightly modified version of a comment on #1661

---
This change is [Reviewable](https://reviewable.io/reviews/dpkp/kafka-python/1694)

### CODE REVIEW

**Comment by dpkp** [comment]
python bug report here: https://bugs.python.org/issue31122

It seems like `wrap_socket()` could also raise OSError?

**Comment by danjo133** [comment]
So, that gets raised when a socket disconnects? I would say that is another error. This PR is for OSError that is raised when trying to connect normally. I can add a catch for 31122 as well if you want though. How do you want it handled in that case? should it raise SSLEOFError or set errno to something like ENOTCONN ? If I understand the bug report, then if you get hit by that, then your connection has been closed and you need to try to reconnect in some way, which I guess should be up to the user.

**Comment by danjo133** [comment]
@dpkp Do you want me to do anything more/different with this PR?

**Comment by dpkp** [comment]
We've finally got python 3.7 automated testing working on travis, so I think we're good to go. Would love more test coverage wrt SSL connections though.

**Pull request merged**
