### PR TITLE
updating configs to resolve #1263

### LINKED ISSUE #1263: AssertionError: Unrecognized configs: {'sasl_kerberos_service_name': 'kafka'}
`kafka/producer/kafka.py` and `kafka/consumer/group.py`
 are missing the new parameter for sasl_kerberos_service_name, throwing the assertion error.

**PR coming**

### PR DESCRIPTION
**Pull request by natedogs911**
updated producer and consumer configs to resolve assertion error when using sasl kerberos service name
see #1263

### CODE REVIEW

**Comment by dpkp** [comment]
@natedogs911 With this change landed is SASL/GSSAPI/kerberos now working for you?

**Comment by natedogs911** [comment]
I’m still having trouble, but questioning the environment I’m using. I’m going to try using the Apache Kerby test suite with a localized kdc and Kafka instance. 

- nathanael

**Comment by dpkp** [comment]
Ok, let me know if you find anything. I am very interested in getting this to work smoothly.

**Comment by dpkp** [comment]
fyi, I noticed that this PR was missing an update to KafkaClient. That is required to make sure the configuration is pushed down to the client's BrokerConnections. I pushed the fixup to master.

**Pull request merged**
