### PR TITLE
1701 use last offset from fetch v4 if available

### PR DESCRIPTION
**Pull request by keithks**
We can reproduce #1701 locally 

This PR fixes the issue where sometimes a consumer is stuck reading past certain offsets from a compacted topic if the last few messages from a partition have been removed by compaction and the server supports fetch V4 or above.

---
This change is [Reviewable](https://reviewable.io/reviews/dpkp/kafka-python/1724)

### CODE REVIEW

**Comment by dpkp** [comment]
@tvoinarovskyi thoughts on this?  (lgtm)

**Comment by tvoinarovskyi** [comment]
@dpkp we can merge to mitigate the problem. I wanted to make it same as Java's approuch, but I can do that for the release after.

**Comment by dpkp** [comment]
Sounds good to me -- thanks for the PR!

**Comment by keithks** [comment]
Thanks all.  Wasn't too familiar with the code so happy to have it refactored later -- just needed something to work for right now.

**Pull request merged**
