### PR TITLE
Allow null payload for deletion feature

### PR DESCRIPTION
**Pull request by vshlapakov**
PR for #408.

[Review on Reviewable](https://reviewable.io/reviews/mumrah/kafka-python/409)

### CODE REVIEW

**Comment by dpkp** [comment]
Should we only allow None values if a key is provided? Also I think it is worth adding a comment w/ a link to relevant apache kafka protocol docs.

Shouldn't we add a test or two as well?

**Comment by vshlapakov** [comment]
Yeah, good catch: I think that message with no key and no payload doesn't make sense at all. I'll add a comment with a link and some tests.

**Comment by vshlapakov** [comment]
@dpkp Check it please, do we need to add something else here?

**Comment by vshlapakov** [comment]
The PR is waiting for code review, check it please!

**Comment by vshlapakov** [comment]
Thanks! :dancers:

**Pull request merged**
