### PR TITLE
Add sphinx formatting to hyperlink methods

### PR DESCRIPTION
**Pull request by jeffwidman**
Got tired of scrolling, so I attempted to hyperlink the methods in Sphinx. 

I *think* this is the correct way to format things, but not 100% confident.

### CODE REVIEW

**Comment by dpkp** [comment]
I mostly use `help(method)` in ipython - I dont think this works with that, does it?

**Comment by jeffwidman** [comment]
Color me ignorant on that one.

I don't think it breaks it, so probably no harm in merging but not positive. I should try using `help(method)` myself more often.

**Comment by dpkp** [comment]
it doesn't break in the sense of a stacktrace or error, but it does show the markup which I think is confusing to non-sphinx users: ":meth:`reinit`" doesn't make a lot of sense literally. I wonder if there is a way to have cake and eat it too here?

**Comment by dpkp** [comment]
When I test locally I need a `.` prefix to get the links to work correctly. For example:
```
:meth:`.subscribe`
```

**Comment by jeffwidman** [comment]
That makes sense. I never built it locally, just copied the style I'd seen on other projects. Before I update the PR though, I want to check if this is something you actually want to merge? Wasn't sure that was the case given your comment on `help(method)`

**Comment by jeffwidman** [comment]
Rebased and updated with local refs using the syntax:
    :meth:`.method`

I wasn't sure how to format refs that were local to the project but not to the file... see the references in `kafka/producer/base.py`. That was the only file that had cross-file references.

**Comment by jeffwidman** [comment]
Rebased.

**Comment by dpkp** [comment]
Sorry I left this one lingering for so long!

**Comment by jeffwidman** [comment]
No worries, thanks for merging. Very convenient to have these hyperlinks in RTD.

**Pull request merged**
