### PR TITLE
Fix error var name in _unpack

### PR DESCRIPTION
**Pull request by j2gg0s**

### CODE REVIEW

**Comment by j2gg0s** [comment]
This is a bug. Maybe we should merge it. @dpkp

**Comment by dpkp** [comment]
Agree - unfortunately i'm travelling and dont have access to my laptop. I
plan to merge when i return home in a few days

**Comment by tvoinarovskyi** [comment]
Merged it, don't see any reason not to =)

**Comment by tvoinarovskyi** [comment]
@j2gg0s GJ

**Comment by jeffwidman** [comment]
oops, my bad!

**Pull request merged**
