### PR TITLE
Consume-produce integration test with Snappy codec

### PR DESCRIPTION
**Pull request by sibiryakov**
Hi guys,
Before 1.0.x series consumer was able to detect if message was compressed and use the necessary decompression codec. During refactoring from `kafka.common` to `kafka.structs` this feature was lost. That breaks backwards compatibility. It would be nice if we could merge this test along with getting back lost feature, or figure some other way how to fix it.

### CODE REVIEW

**Comment by dpkp** [comment]
Is this just for the Simple* interfaces? Have you looked at https://github.com/dpkp/kafka-python/blob/master/test/test_producer.py#L25 ? We do end-to-end testing of produce / consume using all compression types.

**Comment by sibiryakov** [comment]
I didn't tested it for Kafka* interfaces, but it's broken for Simple* as you see. This test is passing on my local machine with kafka-python 0.9.5.

**Comment by dpkp** [comment]
Did #684 fix your issue?

**Comment by sibiryakov** [comment]
It looks like it works now!

**Pull request closed without merging**
