### PR TITLE
made errors more obvious

### PR DESCRIPTION
**Pull request by cookingkode**
It was very difficult for me to debug various broker errors. Adding string variants instead of nos help in easier debugging

### CODE REVIEW

**Comment by cookingkode** [comment]
The failure is a KakfaServer Unavailable error..

**Comment by dpkp** [comment]
Can you give an example of the error logging you were having trouble with? I had thought the class name was always included. The standard error formatting is:
```
[Error {errorno}] {__name__}: {msg}
```

**Comment by cookingkode** [comment]
Well it's not..

For example: I get NodeNorReadyError on every fresh boot. I guess connections are  created on demand. Thus when initially requests go out for things like GroupCo-ordinator etc, then the client finds no connection https://github.com/dpkp/kafka-python/blob/master/kafka/client_async.py#L272

The error I get is something like this
2016-07-25 18:38:09,028.28.156042099:kafka.coordinator:123145306509312:ERROR:30790:Error sending GroupCoordinatorRequest_v0 to node 2 [1]

With the change it would appear as 

2016-07-25 18:38:09,028.28.156042099:kafka.coordinator:123145306509312:ERROR:30790:Error sending GroupCoordinatorRequest_v0 to node 2 [NodeNotReadyError]

**Comment by dpkp** [comment]
Are you using master? That error formatting was updated in #760

**Comment by cookingkode** [comment]
i was using 1.2.5  . Will migrate to the 1.2.6 when it comes. thanks!

Can you also please verify about my hypothesis about NodeNotReadyError? That it's benign and it's expected that connections are built on-demand and thus initial errors are expected..

**Comment by dpkp** [comment]
Yes, that is correct.

**Pull request closed without merging**
