### PR TITLE
WIP: KafkaProducer

### PR DESCRIPTION
**Pull request by dpkp**
This PR implements a new asynchronous producer with an interface similar to the new java upstream client.

It currently uses a single background thread and does not support batching.

TODO: support batching; use event loop or multiple threads; use futures instead of callbacks

(this PR is based on #332, will rebase to master if/when that lands separately)

### CODE REVIEW

**Comment by bjoernhaeuser** [comment]
@dpkp is there anything I can do to get help with this PR?

**Comment by dpkp** [comment]
I put it aside for a while in favor of improving the existing producer implementations.  If you think it is useful in current form, I will take a look and maybe merge after 0.9.4 release.  Have you tried it out?

**Comment by bjoernhaeuser** [comment]
No :-) Just trying to get the current state of async-producers (or batching message sending) and stumbled above this PR.

**Comment by dpkp** [comment]
closing in favor of #515

**Pull request closed without merging**
