### PR TITLE
Add python 3.7 support

### PR DESCRIPTION
**Pull request by jeffwidman**
Add Python 3.7 to the tests.

Document 3.7 support on PyPi.

---
This change is [Reviewable](https://reviewable.io/reviews/dpkp/kafka-python/1614)

### CODE REVIEW

**Comment by jeffwidman** [comment]
This passes locally, but seems like it's always timing out on Travis, probably due to having to use the VM builds rather than the docker container builds for python 3.7. This is what `sudo: yes` is implicitly doing here:
https://github.com/dpkp/kafka-python/pull/1614/files#diff-354f30a63fb0907d4ad57269548329e3R21

**Comment by jeffwidman** [comment]
See also https://github.com/dpkp/kafka-python/issues/1549, this seems to be a valid issue but doesn't appear until 3.7.

**Comment by jeffwidman** [comment]
> I feel like we have a bit too many jobs for our test runners.

And we need to add the 2.X Kafka brokers, so it will only get worse... I have thought several times about cutting down, but I am hesitant to do so on the broker versions as many of those are in production and they do have significant differences... maybe we should drop 3.4/3.5 from the travis matrix as most folks on python 3 tend to stay reasonably up to date

> a more recent Kafka version (>=0.11), that may (maybe) help with timeouts.

Oh, I hadn't thought of that, good idea

**Comment by jeffwidman** [comment]
> run all brokers for 2.7 and latest python + 1 broker per other python versions.

That sounds reasonable to me. I may not get to it soon, so feel free to do it if you get time (and no worries if you don't).

Also, to put this in context... I typically look at the PR and then decide whether / which tests actually matter... ie, if it's straightforward and just needs to be tested against all brokers, then if some random python 3 version times out, I will often immediately merge.

So IMO it's not too bad to have exhaustive test matrix as long as we're not too hung up on retrying builds that timed out just to make them green if we're comfortable making the judgement call that the scope of the PR doesn't create an edge case that matters for it.

**Comment by dpkp** [comment]
Test failure seems like there's a different java setup for this new test configuration and it is preventing Zookeeper (maybe also Kafka) from starting.

```
Error: A fatal exception has occurred. Program will exit.Unrecognized VM option 'UseParNewGC'
Error: Could not create the Java Virtual Machine.
```

**Comment by jeffwidman** [comment]
> Test failure seems like there's a different java setup for this new test configuration and it is preventing Zookeeper (maybe also Kafka) from starting.

That's probably because of the Travis workaround: https://github.com/dpkp/kafka-python/pull/1614/files#diff-354f30a63fb0907d4ad57269548329e3R11

I'm glad it at least got that far, IIRC (it's been a little while) originally I kept seeing timeouts before even getting to that point.

It'd probably be better to switch to the `G1GC` for all the Java builds that support it. But this isn't something I am focused on right now... first I want to get #1193 and then fix some bugs with the new `KafkaAdmin`... hopefully have some PRs inbound there in the next few days.

**Comment by cclauss** [comment]
Travis xenial is now official but not the default: https://blog.travis-ci.com/2018-11-08-xenial-release

That makes the workaround, less of a hack so why not try putting these lines at the top of the .travis.yml file:
```
dist: xenial    # required for Python >= 3.7 (travis-ci/travis-ci#9069)
sudo: required  # required for Python >= 3.7 (travis-ci/travis-ci#9069)
```

**Comment by dpkp** [comment]
I think we need to continue running tests w/ Java 8 (there are some strange failures on the older kafka versions when trying to run w/ Java 11). Unfortunately I haven't figured out how to get jdk8 installed with the new travis xenial image. I opened a forum post here: https://travis-ci.community/t/how-to-use-java8-in-a-python-non-java-project-on-xenial/1823

**Pull request merged**
