### PR TITLE
Fix infinite loops and cpu overflow

### PR DESCRIPTION
**Pull request by Paco112**
Fix multiple infinite loops (locks threads) if connection error :
- Add option "max_retry_backoff" to consomer and producer for more control of retries
- Add Raising connection error if consomer or producer disconnected
- Fix cpu overflow on connection error

### CODE REVIEW

**Comment by Paco112** [comment]
My program uses many processes with consumers and producers. When a kafka connection loss occuring I want my processes to quit automatically after a failure number set by max_retry_backoff. I also wish my main program could send a signal with a JoinableQueue to turn off a process on demand. The problem is that when the connection with kafka is lost, my processes get loop indefinitely and therefore does not quit until the connection with kafka is back. Also I observed that processes with a producer made the cpu go up 100%  after the connection loss for several minutes, which no longer occurs with the commit "cpu overflow". I also find it interesting to have a "ConnectionError" error feedback when the consumer or producer is in "disconneted" status.

With these different fix I no longer have any infinite blocking in my program and a more control over what I have to do in case of connection loss.

I will soon send you a sample code to reproduce all the problems exposed

**Comment by Paco112** [comment]
Here is an example program to show you the infinite blocking problem when you lose a connection with kafka.

To test it is enough to create several topics, launch the program, wait for the children processes spawn and stop kafka.

Once kafka is stopped the program is completely frozen and the exit signals do not stop the program.

However if you test with my pull request and uncommented "max_retry_backoff=1" the program no longer crashes when cutting kafka and child processes this closes correctly, then this restarts as soon as kafka is back.

`from kafka import KafkaConsumer, KafkaProducer
from kafka.structs import TopicPartition
from kafka.errors import ConnectionError, NoBrokersAvailable, KafkaTimeoutError
from multiprocessing import Process, JoinableQueue
from time import sleep
from signal import signal, SIGINT, SIGQUIT, SIGTERM, SIGUSR1

exit_send = False

def exit_signal(signum, stack):
    global exit_send
    print('Exit signal ... {}'.format(signum))
    exit_send = True

def get_partitions(consumer):
    ret_partitions = {}
    topics = sorted(consumer.topics())
    for _topic in topics:
        ret_partitions[_topic] = consumer.partitions_for_topic(_topic)
    return ret_partitions

def partition_lag(consumer, topic_partitions):
    offsets = consumer.end_offsets([topic_partitions])
    committed = consumer.committed(topic_partitions)
    if committed is None:
        committed = 0
    return offsets[topic_partitions] - committed

def create_lag(producer, topic_part):
    producer.send(topic_part.topic, b'test', partition=topic_part.partition)
    producer.flush(30)

class process_test(Process):

    def __init__(self, kafka_servers, topic_parts, queue):
        Process.__init__(self)
        self.kafka_servers = kafka_servers
        self.topic_partition = topic_parts
        self.queue = queue
        try:
            self.consumer = KafkaConsumer(
                bootstrap_servers=kafka_servers,
                group_id='test',
                enable_auto_commit=False,
                consumer_timeout_ms=30000,
                max_poll_records=1,
                #max_retry_backoff=1
            )
            self.producer = KafkaProducer(
                bootstrap_servers=kafka_servers,
                linger_ms=1000,
                batch_size=16384,
                max_block_ms=30000,
                #max_retry_backoff=1
            )
        except NoBrokersAvailable as e:
            print('Exit process {} - {} : {}'.format(self.topic_partition.topic, self.topic_partition.partition, e))
            exit(1)

    def run(self):
        print('Start process {} - {}'.format(self.topic_partition.topic, self.topic_partition.partition))
        self.consumer.assign([topic_partition])
        while self.queue.empty():
            try:
                works = self.consumer.poll(timeout_ms=1000)
                if works is not None:
                    for partition in works.keys():
                        for message in works[partition]:
                            for i in range(0, 100):
                                self.producer.send(topic_partition.topic, b'test', partition=topic_partition.partition)
                    self.consumer.commit()
            except (ConnectionError, NoBrokersAvailable) as e:
                print('Exit process {} - {} : {}'.format(self.topic_partition.topic, self.topic_partition.partition, e))
                exit(1)
            except:
                pass
        self.consumer.close()
        self.producer.close()
        self.queue.task_done()
        print('End process {} - {}'.format(self.topic_partition.topic, self.topic_partition.partition))

if __name__ == "__main__":

    # Init all exit signal
    for sig in [SIGINT, SIGQUIT, SIGTERM, SIGUSR1]:
        signal(sig, exit_signal)

    _kafka_servers = '192.168.70.128:9092'
    _consumer = None
    _producer = None

    try:
        _consumer = KafkaConsumer(
            bootstrap_servers=_kafka_servers,
            group_id='test',
            enable_auto_commit=False,
            consumer_timeout_ms=30000
        )
        _producer = KafkaProducer(
            bootstrap_servers=_kafka_servers,
            linger_ms=1000,
            batch_size=16384,
            max_block_ms=30000,
        )
    except NoBrokersAvailable as e:
        print(e)
        exit(1)

    command_queues = {}
    processes = {}

    while not exit_send:
        try:
            partitions = get_partitions(_consumer)
            for topic, all_partition in partitions.items():
                for p in all_partition:
                    topic_partition = TopicPartition(topic, p)
                    lag = partition_lag(_consumer, topic_partition)
                    if lag and (topic_partition not in processes or not processes[topic_partition].is_alive()):
                        command_queues[topic_partition] = JoinableQueue()
                        processes[topic_partition] = process_test(_kafka_servers, topic_partition, command_queues[topic_partition])
                        processes[topic_partition].start()
                    elif not lag:
                        create_lag(_producer, topic_partition)
        except (ConnectionError, KafkaTimeoutError):
            pass
        sleep(1)

    if len(processes):
        for topic_partition in processes:
            print('Push exit signal to {} - {}'.format(topic_partition.topic, topic_partition.partition))
            command_queues[topic_partition].put('exit')
            processes[topic_partition].join()
`

**Comment by dpkp** [comment]
I am closing this PR because I do not think there has been sufficient explanation or discussion of the underlying issues. My current opinion is that we should not add any blocking behavior to BrokerConnection.connect() [this PR adds a time.sleep call]. Further, I think the desire to raise some exception to the user on broker failures is understandable but needs more discussion / thought. I would prefer that you summarize your thoughts on that via an issue first before moving to a PR implementation.

**Comment by mbande** [comment]
relates to #1322

**Pull request closed without merging**
