### PR TITLE
use python standard max value

### PR DESCRIPTION
**Pull request by lukekingbru**
Use "9999999999" or "999999999" for max value might be not proper. This is a little bit misleading and might cause potential issues.

### CODE REVIEW

**Comment by dpkp** [comment]
Apologies -- all test fixtures were failing due to an unrelated issue. Please pull latest changes from master and re-run tests.

**Comment by lukekingbru** [comment]
Hi dpkp, 

Do I need to give a new pull request to trigger the CI build test, or I can somehow restart the test manually ?

-Luke

**Comment by dpkp** [comment]
You can pull master, rebase, and force push the update back to your branch (or you can merge and push the merge commit).

**Comment by dpkp** [comment]
Thanks!

**Comment by lukekingbru** [comment]
Sure. If you have bugs or features need to tackle, please let me know. I'd like to help.

**Comment by jeffwidman** [comment]
@lukekingbru I recommend skimming https://github.com/dpkp/kafka-python/issues for any issues that have a KAFKA-XXXX jira ticket attached or a KIP attached... those are ones we generally know we want to implement. For example #1122 might be a good one.

**Comment by lukekingbru** [comment]
Thanks so much, Let me dig into it.

**Pull request merged**
