### PR TITLE
Support alternative lz4framed

### PR DESCRIPTION
**Pull request by everpcpc**
Add support for https://github.com/Iotic-Labs/py-lz4framed

### CODE REVIEW

**Comment by jeffwidman** [comment]
Are there tests that should also be updated to run using this new library as well?

**Comment by everpcpc** [comment]
Tests added, but maybe it's too much to add this for all python envs?

**Comment by everpcpc** [comment]
I replaced `lz4` with `py-lz4framed` in the test and travis-ci seems OK. I'll remove this later.
It's maybe not necessary to add tests for this. Because `lz4f` is also not test. And it takes too long based on current tests.

**Comment by dpkp** [comment]
Looks great, thanks!

**Pull request merged**
